from dataclasses import dataclass, field


@dataclass
class ToolStep:
    """
    Represents a single tool execution step.
    """

    tool: str
    parameters: dict = field(default_factory=dict)


@dataclass
class QueryPlan:
    """
    Execution plan generated by the Query Analyzer.

    The orchestrator executes each ToolStep in order.
    """

    intent: str

    steps: list[ToolStep] = field(default_factory=list)

    confidence: float = 1.0

    multi_step: bool = False